export default [
  {
    id: '1',
    name: 'Lucía Pérez',
    lastMessage: 'Tú también 💤',
    time: '21:35',
    messages: [
      { id: 'm1', text: 'Hola Lucía', from: 'me', time: '21:15' },
      { id: 'm2', text: '¡Hola! ¿Cómo estás?', from: 'other', time: '21:16' },
      { id: 'm3', text: 'Bien, terminando unos trabajos del curso', from: 'me', time: '21:17' },
      { id: 'm4', text: '¿Y tú?', from: 'me', time: '21:17' },
      { id: 'm5', text: 'También, algo cansada. Hoy fue pesado', from: 'other', time: '21:18' },
      { id: 'm6', text: '¿Quedamos para mañana en la mañana?', from: 'me', time: '21:20' },
      { id: 'm7', text: 'Sí, a las 10 está bien 😊', from: 'other', time: '21:21' },
      { id: 'm8', text: 'Genial, nos vemos entonces', from: 'me', time: '21:22' },
      { id: 'm9', text: 'Descansa entonces 😴', from: 'other', time: '21:24' },
      { id: 'm10', text: 'Tú también 💤', from: 'me', time: '21:35' },
    ],
  },
  {
    id: '2',
    name: 'Carlos Romero',
    lastMessage: 'Ok, gracias otra vez.',
    time: '16:42',
    messages: [
      { id: 'm11', text: 'Carlos, ¿tienes el informe?', from: 'me', time: '16:30' },
      { id: 'm12', text: 'Sí, te lo envío por WhatsApp', from: 'other', time: '16:31' },
      { id: 'm13', text: 'Perfecto, gracias!', from: 'me', time: '16:32' },
      { id: 'm14', text: '¡Listo! Revisa si te llegó.', from: 'other', time: '16:35' },
      { id: 'm15', text: 'Sí, ya lo tengo.', from: 'me', time: '16:36' },
      { id: 'm16', text: 'Cualquier cosa me avisas.', from: 'other', time: '16:40' },
      { id: 'm17', text: 'Ok, gracias otra vez.', from: 'me', time: '16:42' },
    ],
  },
  {
    id: '3',
    name: 'Grupo - Clases 2025',
    lastMessage: '¡Vamos equipo!',
    time: '08:14',
    messages: [
      { id: 'm18', text: 'Buenos días, grupo.', from: 'other', time: '08:00' },
      { id: 'm19', text: '¿Ya está listo el PPT?', from: 'me', time: '08:01' },
      { id: 'm20', text: 'Sí, lo tiene Ana.', from: 'other', time: '08:02' },
      { id: 'm21', text: '¿Quién presenta hoy?', from: 'other', time: '08:03' },
      { id: 'm22', text: 'Me toca a mí creo 😅', from: 'me', time: '08:04' },
      { id: 'm23', text: 'Vamos con todo 💪', from: 'other', time: '08:05' },
      { id: 'm24', text: 'Sí, éxito a todos ✨', from: 'me', time: '08:06' },
      { id: 'm25', text: 'ok, vamos ✨', from: 'other', time: '08:07' },
      { id: 'm26', text: '¡Estamos listos!', from: 'me', time: '08:10' },
      { id: 'm27', text: '¡Vamos equipo!', from: 'other', time: '08:14' },
    ],
  },
];
